# Supabase config
project_id = "hia-bunchee-bot"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[studio]
enabled = true
port = 54323
api_url = "http://127.0.0.1"

[functions.line-webhook]
verify_jwt = false

[auth]
enabled = true
site_url = "http://127.0.0.1:3000"
